Commit of changes to CI service for the rOps EQ CI page redesign
ONSdigital/ras-collection-instrument pull request #298
Opened 2023-02-24 15:15 UTC by SteveScorfield

# What and why?
As part of the rOps redesign, a new endpoint was required that would allow for a user to add and remove CIs in one go via the rOps CI page. This endpoint deals with both adding and removing CIs in one database transaction. Any failures will roll back the changes and the offending action (add or remove) will be reported to the user. 

# How to test?
Add and remove CIs in rOps. 
Run the unit tests
Run acceptance tests

Trello
https://trello.com/c/ELDnXWO2/2344-rops-design-improvements-ci-page-redesign

Jira
https://jira.ons.gov.uk/browse/RAS-266

2023-02-24 15:18 UTC, SteveScorfield commented
![](https://github.trello.services/images/mini-trello-icon.png) [rOps design improvements - CI page redesign](https://trello.com/c/ELDnXWO2/2344-rops-design-improvements-ci-page-redesign)

2023-02-24 15:22 UTC, SteveScorfield commented
/deploy scorfs

2023-02-27 08:41 UTC, SteveScorfield commented
/deploy scorfs

2023-02-27 11:04 UTC, LJBabbage requested changes
The code works, but it needs a bit of refactoring and refinement, coverage is a little short, although the changes below might sort that out. We might want to consider having a test for a db failure rather than publish one

2023-02-27 11:19 UTC, SteveScorfield commented on application/controllers/collection_instrument.py
> +    def multi_instrument_selection_to_exercise(self, instrument_selection, exercise_id, session=None):
That makes sense. I've updated this.

2023-02-27 11:21 UTC, SteveScorfield commented on application/controllers/collection_instrument.py
> +        validate_uuid(exercise_id)
That's been moved

2023-02-27 13:59 UTC, SteveScorfield commented on application/controllers/collection_instrument.py
> +        linked_instruments = query_exercise_by_id(exercise_id, session)
It returns everything related to that exercise, including all the CIs. By using this, we don't need to call any other queries to get more info.

2023-02-27 16:01 UTC, LJBabbage commented on application/controllers/collection_instrument.py
> +        linked_instruments = query_exercise_by_id(exercise_id, session)
It's the name I was suggesting should be exercise as that is the return on the query

2023-03-02 09:37 UTC, SteveScorfield commented
/deploy scorfs

2023-03-02 16:27 UTC, LJBabbage requested changes
Looking much better, a slightly strange test is the only real thing I can see

2023-03-02 16:27 UTC, LJBabbage commented on application/controllers/collection_instrument.py
> +        # This query will eitheer create a CE (with no CIs attached) or will pull in all linked CIs for the exercise id
Minor typo

2023-03-02 16:27 UTC, LJBabbage commented on application/controllers/collection_instrument.py
> +        Link a collection instrument to a collection exercise
Just needs a tweak in description

2023-03-13 15:07 UTC, SteveScorfield commented
/deploy scorfs

2023-03-14 10:51 UTC, SteveScorfield commented
/deploy scorfs

2023-03-14 14:35 UTC, JacobHarrisonONS commented
/deploy harrisonj

2023-03-15 08:34 UTC, SteveScorfield commented
/deploy scorfs

2023-03-15 12:14 UTC, merged