RAS-1238 Update to docker compose from docker-compose
ONSdigital/ras-collection-instrument pull request #334
Opened 2024-08-01 13:14 UTC by arroyoAle

# What and why?

# How to test?

# Jira

2024-08-02 12:56 UTC, anwilkie reviewed
This PR is fine, but you won't be able to merge this in until the signed commits are implemented for this repo, which I've done it as part of [this PR](https://github.com/ONSdigital/ras-collection-instrument/pull/335).

2024-08-06 14:35 UTC, matthew-robinson-ons commented on Pipfile.lock
Lots of changes in here, was it meant to be checked in?

2024-08-06 14:36 UTC, matthew-robinson-ons requested changes
Quite a lot of changes to the pipfile.lock are they all needed?

2024-08-07 12:10 UTC, anwilkie commented on Pipfile.lock
The changes to the dockerfile are similar to the changes I made in my recent PR, so it should be okay.

2024-08-08 07:50 UTC, arroyoAle commented on Pipfile.lock
I've updated it to specifically target the ones with vulnerabilities

2024-08-08 07:54 UTC, arroyoAle commented
> This PR is fine, but you won't be able to merge this in until the signed commits are implemented for this repo, which I've done it as part of [this PR](https://github.com/ONSdigital/ras-collection-instrument/pull/335).

I've added the signing step

2024-08-08 08:04 UTC, matthew-robinson-ons approved these changes

2024-08-09 06:49 UTC, arroyoAle commented
recreated on https://github.com/ONSdigital/ras-collection-instrument/pull/336 with bot signing

2024-08-09 06:49 UTC, closed without merging