recreate dockerfile branch with signed commits
ONSdigital/ras-collection-instrument pull request #335
Opened 2024-08-01 14:00 UTC by anwilkie

# What and why?
This PR moves the dockerfile to the _infra/docker directory and adds signed commits.

# How to test?
Check GA build.

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-313)

2024-08-02 10:45 UTC, arroyoAle approved these changes
looks good, build works, and docker compose works as expected

2024-08-05 08:17 UTC, matthew-robinson-ons commented on Pipfile.lock
Was this supposed to be updated?

2024-08-05 08:17 UTC, matthew-robinson-ons requested changes
There are a lot of changes in the pipfile.lock which i can't see documented. Will be hard to work out what has gone wrong if something breaks.

2024-08-07 11:41 UTC, anwilkie commented on Pipfile.lock
Yes, there were vulnerabilities that required dependency updates.

2024-08-08 13:47 UTC, anwilkie commented on Pipfile.lock
I ran commands to update the specific packages in question. I don't know why the other packages got updated; I think that's just how pipenv works sometimes. If you're concerned about those updates, feel free to deploy the PR to your environment and test it out.

2024-08-09 08:07 UTC, matthew-robinson-ons commented on Pipfile.lock
You can use `pipenv upgrade` to update a specific package and use pipenv graph to display the dependencies so you can target the correct package and subpackages. Your card doesn't have any runtime changes but by updating all those packages it now does and the testing for it is a lot more in-depth than 'check GA build'. Aiming to make the smallest number of necessary changes seems t]like the better approach to me than just checking in a load of stuff that we don't know the effects of.

2024-08-09 13:23 UTC, matthew-robinson-ons approved these changes
Looks good and dependencies/vulnerabilites updated

2024-08-12 08:44 UTC, merged